name: Mesh-test-service-go build

on:
  push:
    paths:
      - 'mesh-test-service-go/**'
      - '.github/mesh-test-service-go-docker-config.json'
      - '.github/workflows/mesh-test-service-go-on-commit.yaml'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'mesh-test-service-go/**' 
      - '.github/mesh-test-service-go-docker-config.json'
      - '.github/workflows/mesh-test-service-go-on-commit.yaml'

jobs:
  build:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@v1.2.1
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    needs: [build]
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@v1.2.1
    with:
      dry-run: false
      config-filename: mesh-test-service-go-docker-config.json    
  