name: Mesh-integration-tests build

on:
  push:
    paths:
      - 'mesh-integration-tests/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'mesh-integration-tests/**'

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/maven-build-with-sonar.yaml@v1.3.3
    with:
      event-name: ${{ github.event_name }}
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      upload-artifact: false
      pom-file-path: mesh-integration-tests/pom.xml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}    
